# Units for all supported phenomena and main sensors
PHENOMENON_UNITS = {
    "pm1": "µg/m³",
    "pm25": "µg/m³",
    "pm10": "µg/m³",
    "no2_ug": "µg/m³",
    "no2_ppb": "ppb",
    "no_ug": "µg/m³",
    "no_ppb": "ppb",
    "o3_ug": "µg/m³",
    "o3_ppb": "ppb",
    "co_mg": "mg/m³",
    "co_ppm": "ppm",
    "so2_ug": "µg/m³",
    "so2_ppb": "ppb",
    "nh3_ug": "µg/m³",
    "nh3_ppb": "ppb",
    "h2s_ug": "µg/m³",
    "h2s_ppb": "ppb",
    "gamma": "nSv/h",
    "temperature": "°C",
    "humidity": "%",
    "pressure_pa": "hPa",
    # Main sensors (if any units needed)
    "longitude": None,
    "latitude": None,
    "type_name": None,
    "aqi": None,
    "last_measurement_at": None,
}
